### ISSUE TITLE
fix 3 broken test for inAdapters/fileAdapter, fix http not existing, increase coverage on mail adapter

### ISSUE THREAD

**Issue by thomasmodeneis** [guyellis/http-status-check#47]
```
 3 failing

  1) inAdapters/fileAdapter/ getRunData() should return checksites.js data if exists:

      AssertionError: expected 'samplesites' to equal 'checksites'
      + expected - actual

      -samplesites
      +checksites
      
      at Context.<anonymous> (test/lib/inAdapters/test.fileAdapter.js:35:27)

  2) inAdapters/fileAdapter/ getRunData() should return samplesites.js data if exists and if checksites.js is missing:
     Error: Expecting HTTP_STATUS_CHECK_FILE environment or checksites.js or samplesites.js to exist.
      at findFile (lib/inAdapters/fileAdapter.js:19:11)
      at Object.getRunData (lib/inAdapters/fileAdapter.js:24:14)
      at Context.<anonymous> (test/lib/inAdapters/test.fileAdapter.js:56:31)

  3) inAdapters/fileAdapter/ getRunData() should throw an exception if neither samplesites.js or checksites.js exist:

      AssertionError: expected 2 to equal 3
      + expected - actual

      -2
      +3
      
      at Context.<anonymous> (test/lib/inAdapters/test.fileAdapter.js:79:34)


```

fix http not existing, now is https
```
$ npm run start

> http-status-check@1.1.0 start /opt/pocs/http-status-check
> node index.js

X Comentarismo API (http://www.linksilk.com) failed. Here are the problems:
  - Expected header 'location' to be http://linksilk.com/ but instead it was https://linksilk.com/
A total of 6 URIs were tested.
Failure count:  1
Success count:  4
Disable count:  1
```

Increase coverage:
```
=============================== Coverage summary ===============================
Statements   : 78.71% ( 196/249 )
Branches     : 73.27% ( 74/101 )
Functions    : 82.35% ( 28/34 )
Lines        : 78.63% ( 195/248 )
================================================================================
```

By adding test.emailAdapter.js Now coverage is:
```
=============================== Coverage summary ===============================
Statements   : 93.57% ( 233/249 )
Branches     : 81.19% ( 82/101 )
Functions    : 91.18% ( 31/34 )
Lines        : 93.55% ( 232/248 )
================================================================================
```

**Comment by guyellis** [comment]
Fixed by @thomasmodeneis PR
